robotName: "slam"
modelName: "slam"
colorMode: "Textures"
jointNames:
  - ""
pelvisLink: "base"
headLink: "base"
grid_z_offset: 0.49
quadruped: "True"
sensors:
  mode: "wired"
  camera:
    depth:
      - name: "front camera"
        namespace: "depth_camera_front/aligned_depth_to_color"
    color:
      - name: "front camera"
        namespace: "/wide_angle_camera_front/color"
  lidar:
    topic: "/point_cloud_filter/lidar/point_cloud_filtered"
perceptionSources:
empty:


